/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameJoinRouteImport } from './routes/game/join'
import { Route as GameCreateRouteImport } from './routes/game/create'
import { Route as GameRoomIdRouteImport } from './routes/game/$roomId'
import { Route as DevBoxesRouteImport } from './routes/dev/boxes'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiGameWsRoomIdRouteImport } from './routes/api/game/ws.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameJoinRoute = GameJoinRouteImport.update({
  id: '/game/join',
  path: '/game/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCreateRoute = GameCreateRouteImport.update({
  id: '/game/create',
  path: '/game/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomIdRoute = GameRoomIdRouteImport.update({
  id: '/game/$roomId',
  path: '/game/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBoxesRoute = DevBoxesRouteImport.update({
  id: '/dev/boxes',
  path: '/dev/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameWsRoomIdRoute = ApiGameWsRoomIdRouteImport.update({
  id: '/api/game/ws/$roomId',
  path: '/api/game/ws/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/boxes': typeof DevBoxesRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/game/create': typeof GameCreateRoute
  '/game/join': typeof GameJoinRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/game/ws/$roomId': typeof ApiGameWsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/boxes': typeof DevBoxesRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/game/create': typeof GameCreateRoute
  '/game/join': typeof GameJoinRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/game/ws/$roomId': typeof ApiGameWsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/boxes': typeof DevBoxesRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/game/create': typeof GameCreateRoute
  '/game/join': typeof GameJoinRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/game/ws/$roomId': typeof ApiGameWsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev/boxes'
    | '/game/$roomId'
    | '/game/create'
    | '/game/join'
    | '/api/trpc/$'
    | '/api/game/ws/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev/boxes'
    | '/game/$roomId'
    | '/game/create'
    | '/game/join'
    | '/api/trpc/$'
    | '/api/game/ws/$roomId'
  id:
    | '__root__'
    | '/'
    | '/dev/boxes'
    | '/game/$roomId'
    | '/game/create'
    | '/game/join'
    | '/api/trpc/$'
    | '/api/game/ws/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevBoxesRoute: typeof DevBoxesRoute
  GameRoomIdRoute: typeof GameRoomIdRoute
  GameCreateRoute: typeof GameCreateRoute
  GameJoinRoute: typeof GameJoinRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiGameWsRoomIdRoute: typeof ApiGameWsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/join': {
      id: '/game/join'
      path: '/game/join'
      fullPath: '/game/join'
      preLoaderRoute: typeof GameJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/create': {
      id: '/game/create'
      path: '/game/create'
      fullPath: '/game/create'
      preLoaderRoute: typeof GameCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomId': {
      id: '/game/$roomId'
      path: '/game/$roomId'
      fullPath: '/game/$roomId'
      preLoaderRoute: typeof GameRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/boxes': {
      id: '/dev/boxes'
      path: '/dev/boxes'
      fullPath: '/dev/boxes'
      preLoaderRoute: typeof DevBoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/ws/$roomId': {
      id: '/api/game/ws/$roomId'
      path: '/api/game/ws/$roomId'
      fullPath: '/api/game/ws/$roomId'
      preLoaderRoute: typeof ApiGameWsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevBoxesRoute: DevBoxesRoute,
  GameRoomIdRoute: GameRoomIdRoute,
  GameCreateRoute: GameCreateRoute,
  GameJoinRoute: GameJoinRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiGameWsRoomIdRoute: ApiGameWsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
